In [1]:
import numpy as np

**Creating array using numpy.empty**

In [2]:
b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.empty([3, 3])
print("\nMatrix c : \n", c)


Matrix b : 
 [-4611686018427387904           3443163135]

Matrix a : 
 [[101176750418048               0]
 [101176755751904 101176756473648]]

Matrix c : 
 [[4.99879592e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


**Creating array using numpy.zeros**

In [3]:
b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.zeros([3, 3])
print("\nMatrix c : \n", c)


Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Addition Operations**

In [4]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)

# The same functions and operations can be used for
# multiple matrices
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)


[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


**Subtraction Operation**

In [5]:
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)

# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)


[ 3 67  3 70]
[ 3 67  3 70]


**Array Indexing**

In [6]:
# Python program to demonstrate 
# the use of index arrays.

# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)

# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


**Slicing in Numpy**

In [7]:
# Python program for basic slicing.

# Arrange elements from 0 to 19. The last element is indexed by -1 second last by -2 and so on.
a = np.arange(20)
print("\n Array is:\n ",a)

# a[start:stop:step]
print("\n a[-8:17:1] = ",a[-8:17:1])   #The last element is indexed by -1 second last by -2 and so on.

# The : operator means all elements till the end.
print("\n a[10:] = ",a[10:])




 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


**Ellipsis can also be used along with basic slicing. Ellipsis (…) is the number of : objects needed to make a selection tuple of the same length as the dimensions of the array.**

In [8]:
# Python program for indexing using basic slicing with ellipsis

# A 3 dimensional array.
b = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print(b[...,1]) #Equivalent to b[: ,: ,1 ]


[[ 2  5]
 [ 8 11]]


**How to chek the dimension of the array created by numpy**

In [9]:
#Getting dimensions of the array created by numpy

# create numpy arrays
# 1-d numpy array
_1darr = np.arange(4) 
print(_1darr)

# printing the 1-dimensions numpy array
print("Dimensions in _1darr are: ", _1darr.ndim)


[0 1 2 3]
Dimensions in _1darr are:  1


**NumPy Array Broadcasting** :  refers to how numpy treats arrays with different Dimensions during arithmetic operations

In [10]:
macros = np.array([
[0.8, 2.9, 3.9],
[52.4, 23.6, 36.5],
[55.2, 31.7, 23.9],
[14.4, 11, 4.9]
])

# Create a new array filled with zeros,# of the same shape as macros.
result = np.zeros_like(macros)

cal_per_macro = np.array([3, 3, 8])

# Now multiply each row of macros by
# cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
print(macros.shape[0]) # Since shape[0] refers to rows , shape[1] refers to columns
for i in range(macros.shape[0]):
    result[i, :] = macros[i, :] * cal_per_macro

result


4


array([[  2.4,   8.7,  31.2],
       [157.2,  70.8, 292. ],
       [165.6,  95.1, 191.2],
       [ 43.2,  33. ,  39.2]])

**Observation : This results in multiplication of a larger dimensional  array by a smaller array. The smaller array is broadcast across the larger array so that they have compatible shapes.**

<div style="width: 50%; height: 50px;   text-align: left; line-height: 20px; color: black; font-size: 15px; font-color: blue; font-weight: bold; border-radius:2px;">
    Broadcasting Rules: Broadcasting two arrays together follow these rules: </div>
<span >
    If the arrays don’t have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible with all dimensions.
After broadcasting, each array behaves as if it had a shape equal to the element-wise maximum of shapes of the two input arrays.
In any dimension where one array had a size of 1 and the other array had a size greater than 1, the first array behaves as if it were copied along that dimension.
    </span> 




In [11]:
v = np.array([2, 14, 26]) 
w = np.array([5, 15])   

# To compute an outer product we first reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) + w)


[[ 7 17]
 [19 29]
 [31 41]]


In [12]:
X = np.array([[12, 22, 33], [45, 55, 66]])
v = np.array([2, 14, 26]) 

# X has shape 2x3 and v has shape (3, ) so they broadcast to 2x3
print("V is:  \n")
print(v)
print("\n")
print("X is: \n")
print(X)
print("\n")
print("X + v is: \n")
print(X + v)

V is:  

[ 2 14 26]


X is: 

[[12 22 33]
 [45 55 66]]


X + v is: 

[[14 36 59]
 [47 69 92]]
